import './styles.css';
import { BrowserMultiFormatReader } from '@zxing/browser';
import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';

const app=document.querySelector('#app');
const state={page:'home',admin:false,products:[],sales:[],dashboard:null,cart:[],online:navigator.onLine,scanner:null};
const euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n)||0);
const api=async(path,opts={})=>{const r=await fetch(path,{headers:{'content-type':'application/json',...(opts.headers||{})},...opts});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Errore');return d};
const icon=(x)=>x;

window.addEventListener('online',()=>{state.online=true;syncQueue();render()});
window.addEventListener('offline',()=>{state.online=false;render()});

function shell(content){return `<div class="app"><header class="topbar"><div><div class="brand">Gestionale MB</div><div class="muted">${state.admin?'Area amministratore':'Area store'}</div></div><div>${state.online?'<span class="badge ok">Online</span>':'<span class="badge warn">Offline</span>'} ${state.admin?'<button class="btn ghost" id="logout">Esci</button>':'<button class="btn ghost" id="adminLogin">Admin</button>'}</div></header><main class="container">${!state.online?'<div class="notice offline">Sei offline: le operazioni verranno salvate e sincronizzate appena torna Internet.</div>':''}${content}</main>${nav()}</div>`}
function nav(){return `<nav class="bottomnav"><button class="navbtn ${state.page==='home'?'active':''}" data-page="home">⌂<br>Home</button><button class="navbtn ${state.page==='products'?'active':''}" data-page="products">▦<br>Magazzino</button><button class="navbtn scan-main" id="scanNav">⌁</button><button class="navbtn ${state.page==='sales'?'active':''}" data-page="sales">€<br>Vendite</button><button class="navbtn ${state.page==='more'?'active':''}" data-page="more">•••<br>Altro</button></nav>`}

async function refresh(){try{state.products=await api('/api/products');state.sales=await api('/api/sales');state.dashboard=await api('/api/dashboard')}catch(e){console.warn(e)}render()}
function render(){let content='';if(state.page==='home')content=home();if(state.page==='products')content=products();if(state.page==='sales')content=sales();if(state.page==='more')content=more();app.innerHTML=shell(content);bindCommon()}
function home(){const d=state.dashboard||{inventory:{units:0,out_of_stock:0},month:{sales:0,revenue:0,commission:0},top:[],trend:[]};return `<div class="actions"><button class="btn large" id="addProduct">＋ Carica prodotto</button><button class="btn large secondary" id="newSale">⌁ Registra vendita</button></div><div class="grid ${state.admin?'three':'two'}"><div class="card stat"><span class="muted">Prodotti disponibili</span><strong>${d.inventory.units||0}</strong></div><div class="card stat"><span class="muted">Prodotti esauriti</span><strong>${d.inventory.out_of_stock||0}</strong></div><div class="card stat"><span class="muted">Vendite del mese</span><strong>${d.month.sales||0}</strong></div>${state.admin?`<div class="card stat"><span class="muted">Incasso mese</span><strong>${euro(d.month.revenue)}</strong></div><div class="card stat"><span class="muted">Provvigione maturata</span><strong>${euro(d.month.commission)}</strong></div><div class="card stat"><span class="muted">Da incassare</span><strong>${euro(d.month.commission_due)}</strong></div>`:''}</div>${state.admin?adminHome(d):recentOps()}`}
function adminHome(d){const max=Math.max(...(d.trend||[]).map(x=>x.revenue),1);return `<div class="grid two" style="margin-top:14px"><div class="card"><h3>Andamento ultimi 12 mesi</h3><div class="chart">${(d.trend||[]).map(x=>`<div class="bar" style="height:${Math.max(8,x.revenue/max*100)}%"><span>${x.period.slice(5)}</span></div>`).join('')||'<span class="muted">Nessun dato</span>'}</div></div><div class="card"><h3>Prodotti più venduti</h3>${(d.top||[]).slice(0,6).map(x=>`<div style="display:flex;justify-content:space-between;padding:8px 0"><span>${x.brand} ${x.name}</span><strong>${x.qty}</strong></div>`).join('')||'<span class="muted">Nessuna vendita</span>'}</div></div><div class="card" style="margin-top:14px"><h3>Prodotti fermi da oltre 90 giorni</h3>${(d.stale||[]).length?d.stale.map(x=>`<div style="display:flex;justify-content:space-between;padding:8px 0"><span>${x.brand} ${x.name}</span><span class="muted">${x.current_qty} pz</span></div>`).join(''):'<span class="muted">Nessun prodotto fermo.</span>'}</div>`}
function recentOps(){return `<div class="card" style="margin-top:14px"><h3>Ultime vendite</h3>${state.sales.slice(0,6).map(s=>`<div style="display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #eee"><span>${s.sale_code}<br><small class="muted">${new Date(s.occurred_at).toLocaleString('it-IT')}</small></span><strong>${euro(s.total)}</strong></div>`).join('')||'<span class="muted">Nessuna vendita.</span>'}</div>`}
function products(){return `<div class="section-title"><h2>Magazzino</h2><button class="btn" id="addProduct">＋ Nuovo</button></div><div class="toolbar"><input class="input" id="productSearch" placeholder="Cerca codice, nome, marca..."><button class="btn secondary" id="importBtn">Importa CSV/XLSX</button></div><div class="table-wrap"><table><thead><tr><th>Prodotto</th><th>Codice</th><th>Taglia</th><th>Prezzo</th><th>Quantità</th><th>Stato</th><th></th></tr></thead><tbody>${state.products.map(p=>`<tr><td><strong>${p.brand||''} ${p.name||'Senza nome'}</strong><br><small class="muted">${p.category||''} ${p.color||''}</small></td><td>${p.barcode||p.internal_code}</td><td>${p.size||'—'}</td><td>${euro(p.list_price)}</td><td>${p.current_qty}</td><td><span class="badge ${p.current_qty>0?'ok':'bad'}">${p.current_qty>0?'Disponibile':'Esaurito'}</span></td><td><button class="btn ghost editProduct" data-id="${p.id}">Modifica</button></td></tr>`).join('')}</tbody></table></div>`}
function sales(){return `<div class="section-title"><h2>Vendite</h2><button class="btn" id="newSale">＋ Registra</button></div><div class="table-wrap"><table><thead><tr><th>Codice</th><th>Data</th><th>Articoli</th><th>Sconto</th><th>Totale</th><th>Stato</th><th></th></tr></thead><tbody>${state.sales.map(s=>`<tr><td>${s.sale_code}</td><td>${new Date(s.occurred_at).toLocaleString('it-IT')}</td><td>${s.items_count}</td><td>${euro(s.discount_total)}</td><td><strong>${euro(s.total)}</strong></td><td><span class="badge ${s.status==='completed'?'ok':'bad'}">${s.status==='completed'?'Completata':'Annullata'}</span></td><td><button class="btn ghost saleDetail" data-id="${s.id}">Apri</button></td></tr>`).join('')}</tbody></table></div>`}
function more(){return `<h2>Strumenti</h2><div class="grid two"><button class="card btn secondary" id="movementsBtn">Storico movimenti</button>${state.admin?'<button class="card btn secondary" id="commissionsBtn">Provvigioni</button><button class="card btn secondary" id="auditBtn">Registro attività</button><button class="card btn secondary" id="exportBtn">Esporta report</button>':''}</div><div class="card" style="margin-top:14px"><h3>Installazione su iPhone</h3><p class="muted">Apri il sito in Safari, premi Condividi e scegli “Aggiungi alla schermata Home”.</p></div>`}

function bindCommon(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});document.querySelector('#scanNav')?.addEventListener('click',()=>openScanner('sale'));document.querySelectorAll('#addProduct').forEach(b=>b.onclick=()=>openProduct());document.querySelectorAll('#newSale').forEach(b=>b.onclick=()=>openScanner('sale'));document.querySelector('#adminLogin')?.addEventListener('click',openLogin);document.querySelector('#logout')?.addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST'});state.admin=false;render()});document.querySelectorAll('.editProduct').forEach(b=>b.onclick=()=>openProduct(state.products.find(x=>x.id==b.dataset.id)));document.querySelectorAll('.saleDetail').forEach(b=>b.onclick=()=>openSaleDetail(b.dataset.id));document.querySelector('#productSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')});document.querySelector('#importBtn')?.addEventListener('click',openImport);document.querySelector('#movementsBtn')?.addEventListener('click',openMovements);document.querySelector('#commissionsBtn')?.addEventListener('click',openCommissions);document.querySelector('#auditBtn')?.addEventListener('click',openAudit);document.querySelector('#exportBtn')?.addEventListener('click',exportMenu)}
function modal(html){const el=document.createElement('div');el.className='modal';el.innerHTML=`<div class="modal-panel"><div class="modal-head"><h2 style="margin:0">${html.title||''}</h2><button class="close">×</button></div>${html.body}</div>`;document.body.appendChild(el);el.querySelector('.close').onclick=()=>{state.scanner?.reset?.();el.remove()};return el}
function openLogin(){const m=modal({title:'Accesso amministratore',body:`<form id="loginForm"><div class="field"><label>Email</label><input class="input" name="email" type="email" value="effestrategy@gmail.com"></div><div class="field" style="margin-top:12px"><label>Password</label><input class="input" name="password" type="password" required></div><button class="btn" style="width:100%;margin-top:16px">Accedi</button></form>`});m.querySelector('form').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));try{await api('/api/auth/login',{method:'POST',body:JSON.stringify(o)});state.admin=true;m.remove();refresh()}catch(err){alert(err.message)}}}
function openProduct(p={}){const m=modal({title:p.id?'Modifica prodotto':'Nuovo prodotto',body:`<form id="productForm"><div class="form-grid">${[['barcode','Codice a barre'],['name','Nome'],['brand','Marca'],['category','Categoria'],['model','Modello'],['color','Colore'],['size','Taglia'],['season','Stagione'],['list_price','Prezzo vendita'],['cost_price','Costo'],['current_qty','Quantità'],['notes','Note']].map(([n,l])=>`<div class="field"><label>${l}</label><input class="input" name="${n}" type="${n.includes('price')||n==='current_qty'?'number':'text'}" step="${n.includes('price')?'0.01':'1'}" value="${p[n]??''}"></div>`).join('')}</div><button class="btn" style="width:100%;margin-top:16px">Salva prodotto</button></form>`});m.querySelector('form').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));try{if(!state.online){queue({type:p.id?'product_update':'product_create',id:p.id,data:o});m.remove();alert('Salvato offline. Sarà sincronizzato.');return}await api(p.id?`/api/products/${p.id}`:'/api/products',{method:p.id?'PUT':'POST',body:JSON.stringify(o)});m.remove();refresh()}catch(err){alert(err.message)}}}
async function openScanner(mode='sale'){const m=modal({title:mode==='sale'?'Scansiona vendita':'Scansiona prodotto',body:`<div class="scanner"><video id="video"></video><div class="scanner-tip">Inquadra il codice a barre. La scansione resta aperta.</div></div><div style="display:flex;gap:8px;margin-top:12px"><input id="manualCode" class="input" placeholder="Oppure inserisci il codice"><button class="btn" id="manualGo">Cerca</button></div><div id="scanCart" style="margin-top:14px"></div>`});const handle=async code=>{if(m.dataset.busy)return;m.dataset.busy='1';setTimeout(()=>m.dataset.busy='',900);try{const p=await api(`/api/products/lookup/${encodeURIComponent(code)}`);if(mode==='sale'){addCart(p);renderScannerCart(m)}else{m.remove();openProduct(p)}}catch{if(confirm('Prodotto non presente. Vuoi registrarlo?')){m.remove();openProduct({barcode:code,current_qty:1})}}};m.querySelector('#manualGo').onclick=()=>handle(m.querySelector('#manualCode').value.trim());try{const reader=new BrowserMultiFormatReader();state.scanner=reader;const controls=await reader.decodeFromVideoDevice(undefined,m.querySelector('#video'),result=>{if(result){navigator.vibrate?.(80);handle(result.getText())}});state.scanner={reset:()=>controls.stop()}}catch(e){m.querySelector('.scanner-tip').textContent='Fotocamera non disponibile. Usa il campo manuale.'}renderScannerCart(m)}
function addCart(p){const x=state.cart.find(i=>i.product.id===p.id);if(x)x.quantity++;else state.cart.push({product:p,quantity:1,final_unit_price:p.list_price})}
function renderScannerCart(m){const box=m.querySelector('#scanCart');if(!box)return;box.innerHTML=`<h3>Carrello (${state.cart.reduce((a,x)=>a+x.quantity,0)})</h3>${state.cart.map((x,i)=>`<div class="cart-item"><div><strong>${x.product.brand} ${x.product.name}</strong><br><small class="muted">${x.product.barcode||x.product.internal_code}</small></div><input class="input qty" data-i="${i}" type="number" min="1" value="${x.quantity}"><input class="input finalPrice" data-i="${i}" type="number" step="0.01" value="${x.final_unit_price}"><button class="btn danger remove" data-i="${i}">×</button></div>`).join('')||'<p class="muted">Scansiona il primo prodotto.</p>'}<div style="display:flex;justify-content:space-between;align-items:center;margin-top:14px"><strong>Totale: ${euro(state.cart.reduce((a,x)=>a+x.quantity*x.final_unit_price,0))}</strong><button class="btn" id="checkout" ${state.cart.length?'':'disabled'}>Conferma vendita</button></div>`;box.querySelectorAll('.qty').forEach(el=>el.onchange=()=>{state.cart[el.dataset.i].quantity=Math.max(1,+el.value);renderScannerCart(m)});box.querySelectorAll('.finalPrice').forEach(el=>el.onchange=()=>{state.cart[el.dataset.i].final_unit_price=+el.value;renderScannerCart(m)});box.querySelectorAll('.remove').forEach(el=>el.onclick=()=>{state.cart.splice(el.dataset.i,1);renderScannerCart(m)});box.querySelector('#checkout').onclick=()=>checkout(m)}
async function checkout(m){const payload={items:state.cart.map(x=>({product_id:x.product.id,quantity:x.quantity,final_unit_price:x.final_unit_price})),source:'store'};try{if(!state.online){queue({type:'sale_create',data:payload});state.cart=[];m.remove();alert('Vendita salvata offline.');return}const r=await api('/api/sales',{method:'POST',body:JSON.stringify(payload)});state.cart=[];m.remove();alert(`Vendita ${r.sale_code} registrata. Totale ${euro(r.total)}`);refresh()}catch(e){alert(e.message)}}
async function openSaleDetail(id){
  try{
    const s=await api(`/api/sales/${id}`);
    const itemHtml=s.items.map(i=>{
      const canReturn=s.status==='completed' && i.returned_qty<i.quantity;
      const btn=canReturn?`<button class="btn ghost returnBtn" data-id="${i.id}" style="float:right">Reso</button>`:'';
      return `<div class="card" style="margin-bottom:8px"><strong>${i.brand} ${i.name}</strong><br><span>${i.quantity} × ${euro(i.final_unit_price)}</span>${btn}</div>`;
    }).join('');
    const cancelBtn=state.admin && s.status==='completed'?'<button class="btn danger" id="cancelSale" style="width:100%;margin-top:10px">Annulla vendita</button>':'';
    const m=modal({title:`Vendita ${s.sale_code}`,body:`<p><strong>${euro(s.total)}</strong> · ${new Date(s.occurred_at).toLocaleString('it-IT')}</p>${itemHtml}${cancelBtn}`});
    m.querySelectorAll('.returnBtn').forEach(b=>b.onclick=async()=>{const reason=prompt('Motivo del reso:','');if(reason===null)return;await api('/api/returns',{method:'POST',body:JSON.stringify({sale_item_id:+b.dataset.id,quantity:1,reason})});m.remove();refresh()});
    m.querySelector('#cancelSale')?.addEventListener('click',async()=>{const reason=prompt('Motivo annullamento:','');if(reason===null)return;await api(`/api/sales/${id}/cancel`,{method:'POST',body:JSON.stringify({reason})});m.remove();refresh()});
  }catch(e){alert(e.message)}
}
function openImport(){const m=modal({title:'Importa prodotti',body:`<p class="muted">Colonne supportate: barcode, name, brand, category, model, color, size, season, list_price, cost_price, quantity, notes.</p><input type="file" id="file" class="input" accept=".csv,.xlsx,.xls"><button class="btn" id="doImport" style="width:100%;margin-top:12px">Importa</button>`});m.querySelector('#doImport').onclick=async()=>{const f=m.querySelector('#file').files[0];if(!f)return alert('Seleziona un file');const buf=await f.arrayBuffer();const wb=XLSX.read(buf);const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});const r=await api('/api/products/import',{method:'POST',body:JSON.stringify({rows})});alert(`Inseriti: ${r.inserted}\nAggiornati: ${r.updated}\nErrori: ${r.errors.length}`);m.remove();refresh()}}
async function openMovements(){const rows=await api('/api/movements');modal({title:'Storico movimenti',body:`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Prodotto</th><th>Tipo</th><th>Movimento</th><th>Quantità</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('it-IT')}</td><td>${x.brand} ${x.name}</td><td>${x.type}</td><td>${x.quantity>0?'+':''}${x.quantity}</td><td>${x.previous_qty} → ${x.new_qty}</td></tr>`).join('')}</tbody></table></div>`})}
async function openCommissions(){const rows=await api('/api/commissions');const m=modal({title:'Provvigioni mensili',body:`<div class="table-wrap"><table><thead><tr><th>Mese</th><th>Vendite</th><th>Provvigione</th><th>Pagata</th><th>Da incassare</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr><td>${x.period}</td><td>${euro(x.revenue)}</td><td>${euro(x.commission)}</td><td>${euro(x.paid)}</td><td><strong>${euro(x.due)}</strong></td><td><button class="btn ghost pay" data-period="${x.period}" data-amount="${x.commission}">Segna pagata</button></td></tr>`).join('')}</tbody></table></div>`});m.querySelectorAll('.pay').forEach(b=>b.onclick=async()=>{await api('/api/commissions/pay',{method:'POST',body:JSON.stringify({period:b.dataset.period,amount:+b.dataset.amount})});m.remove();openCommissions()})}
async function openAudit(){const rows=await api('/api/audit');modal({title:'Registro attività',body:`<div class="table-wrap"><table><thead><tr><th>Data</th><th>Utente</th><th>Azione</th><th>Elemento</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('it-IT')}</td><td>${x.actor}</td><td>${x.action}</td><td>${x.entity_type} #${x.entity_id||''}</td></tr>`).join('')}</tbody></table></div>`})}
function exportMenu(){const rows=state.sales.map(s=>({Codice:s.sale_code,Data:s.occurred_at,Articoli:s.items_count,Subtotale:s.subtotal,Sconto:s.discount_total,Totale:s.total,Stato:s.status}));const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Vendite');XLSX.writeFile(wb,'report-vendite-mb.xlsx');const pdf=new jsPDF();pdf.text('Gestionale MB - Report vendite',14,18);rows.slice(0,45).forEach((r,i)=>pdf.text(`${r.Data.slice(0,10)}  ${r.Codice}  EUR ${r.Totale}`,14,30+i*5));pdf.save('report-vendite-mb.pdf')}
function queue(item){const q=JSON.parse(localStorage.getItem('mb_queue')||'[]');q.push({...item,queued_at:new Date().toISOString()});localStorage.setItem('mb_queue',JSON.stringify(q))}
async function syncQueue(){const q=JSON.parse(localStorage.getItem('mb_queue')||'[]');if(!q.length)return;const rest=[];for(const x of q){try{if(x.type==='product_create')await api('/api/products',{method:'POST',body:JSON.stringify(x.data)});if(x.type==='product_update')await api(`/api/products/${x.id}`,{method:'PUT',body:JSON.stringify(x.data)});if(x.type==='sale_create')await api('/api/sales',{method:'POST',body:JSON.stringify(x.data)})}catch{rest.push(x)}}localStorage.setItem('mb_queue',JSON.stringify(rest));refresh()}

(async()=>{try{const me=await api('/api/auth/me');state.admin=me.authenticated}catch{}await refresh();syncQueue()})();
